dist: trusty
sudo: required

language: c

branches:
  only:
    - C/C++_inDepProg_2

os: linux

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-6
      - valgrind
      - cppcheck

script:
  - mkdir build
  - cd build
  - cmake ./..
  - make
  - cppcheck --enable=all --std=c99 --check-config --suppress=missingIncludeSystem -I ../includes/ ../For_static_library/
  - cppcheck --enable=all --std=c99 --check-config --suppress=missingIncludeSystem -I ../includes/ ../For_dynamic_library/
  - cppcheck --enable=all --std=c99 --check-config --suppress=missingIncludeSystem -I ../includes/ ../utils/
  - valgrind --tool=memcheck --leak-check=full ./For_dynamic_library/multi_thread_app/multi_thread 1 1 1
  - valgrind --tool=memcheck --leak-check=full ./For_static_library/single_thread_app/single_thread 1 1 1